version: '3.8'
services:
  backend:
    build: ./cassie-backend
    ports:
      - "3002:3000"  # Example: container's port 3000 mapped to host port 3002
    volumes:
      - ./cassie-backend:/app
      - /app/node_modules
    env_file:
      - ./cassie-backend/.env
    environment:
      - NODE_ENV=development

  frontend:
    build: ./cassie-frontend
    ports:
      - "3001:3000"
    volumes:
      - ./cassie-frontend:/app
      - /app/node_modules
    environment:
      - SKIP_PREFLIGHT_CHECK=true
      - WDS_SOCKET_PORT=3001
      - WATCHPACK_POLLING=true
      - NODE_OPTIONS=--openssl-legacy-provider
    stdin_open: true
    tty: true
    depends_on:
      - backend
